spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: lvxus
    password: lvxus
    url: jdbc:oracle:thin:@192.168.255.1:1521:orcl
server:
  port: 8081
  servlet:
    context-path: /